### PR TITLE
Bugfix/type error

### LINKED ISSUE #86: Exception: TypeError: Cannot read property '1280' of undefined
2016-06-07T15:37:30.871Z	bcdeb48b-2cc5-11e6-8ea1-ebbe2cfbc878	TypeError: Cannot read property '1280' of undefined
    at map_large_hotel_images (/var/task/lib/result_mapper.js:27:27)
    at /var/task/lib/result_mapper.js:111:22
    at Array.map (native)
    at Object.map_ne_result_to_graphql (/var/task/lib/result_mapper.js:96:23)
    at /var/task/lib/api_request.js:116:38
    at /var/task/lib/api_request.js:62:16
    at IncomingMessage.<anonymous> (/var/task/lib/http_request.js:28:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)

### LINKED ISSUE #87: Exception: TypeError: Cannot read property 'forEach' of undefined > parse_sns.js:32:23
2016-06-07T15:32:42.208Z	eee33aae-2cc4-11e6-9bff-8d11fc066811	TypeError: Cannot read property 'forEach' of undefined
    at extract_search_params (/var/task/lib/parse_sns.js:32:23)
    at exports.handler (/var/task/index.js:17:16)

### LINKED ISSUE #88: Stop sending hotelIds on search-results SNS topic
the `hotelIds` Array is not necessary, let's remove it.

### PR DESCRIPTION
**Pull request by nelsonic**
Hi @jruts this PR fixes the 3 issues noted today.
+ fixes #86 - when a hotel does not have *any* images
+ fixes #87 - when the UI does not pass through *any* passengers
+ fixes #88 - avoid sending the `hotelIds` (*can be a large list*) to SNS topic.

Please review and let me know if Ok. thanks.

### CODE REVIEW

**Comment by jruts** [comment]
@nelsonic fix #89  is working since we are getting packages back in the ui.

**Comment by nelsonic** [comment]
@jruts yeah, you are 100% correct. I referenced the incorrect issue. should have been: https://github.com/numo-labs/lambda-ne-classic-package-provider/issues/88
Thanks!

**Comment by jruts** [comment]
:+1:

**Comment by jruts** [comment]
I am going to wait because I feel you have an improvement.

File: index.js [hunk 1]
```diff
@@ -48,18 +48,16 @@ exports.handler = function (event, context, callback) {
...
     });
-    var minimised = body;
-    delete minimised.hotelIds; // don't need hotelIds again https://git.io/voIAS
-    minimised.items = [ mapper.minimiseBandwidth(body.items[0]) ];
 
     AwsHelper.saveRecordToS3(body, function (err, data) {
       AwsHelper.log.trace({ err: err }, 'Saved Package to S3');
-      AwsHelper.pushToSNSTopic(minimised, function (err, result) {
+      delete body.hotelIds; // don't need hotelIds again https://git.io/voIAS
+      body.items = [ mapper.minimiseBandwidth(body.items[0]) ]; // minimal fields
```
Comment (lennym) [inline index.js]: I'd be tempted to make this `body.items = body.items.map(mapper.minimiseBandwidth);` so that we're not bound to only ever having one item. It also reads a bit clearer IMO.

**Comment by nelsonic** [comment]
@jruts 📥

File: index.js (hunk 1 above)
Comment (nelsonic) [inline index.js]: @lennym I was operating under the *assumption* that only *one* result (item) would be emitted at a time, but you're right, that's *way* bettererer and the code is cleaner. *Thanks*! ✅
